feat: add puppeteer testing for e2e login checks
ndlib/QA_tests pull request #370
Opened 2021-05-07 16:59 UTC by ialford

Due to the nature of the way SPAs are rendered in the browser, selenium doesn't work very well as a testing framework. This adds tests written in Puppeteer, which is a Node library and allows promises to be used as we wait for content to be rendered in the browser, making the front end tests more reliable. 

The tests are also written in a jest style format, making them as approachable as unit tests for some. 

Here, we add two basic tests for expected content - that the browser is going to the right place and that a login button that works is present - along with an end-to-end login check, if appropriate ENV is leveraged. Instructions are in the README for both the Docker build/test and running the test suite without Docker.

Closes ESU-1142

2021-05-07 18:42 UTC, wsill requested changes
Will you need to update some of the packages so that all the tests pass?

2021-05-07 18:44 UTC, ialford commented
> Will you need to update some of the packages so that all the tests pass?

I can add updates to the Chrome container, sure. Would you prefer that happen in this PR or that it be addressed in a subsequent PR? @wsill

2021-05-07 18:49 UTC, wsill commented
> > Will you need to update some of the packages so that all the tests pass?
> 
> I can add updates to the Chrome container, sure. Would you prefer that happen in this PR or that it be addressed in a subsequent PR? @wsill



> > Will you need to update some of the packages so that all the tests pass?
> 
> I can add updates to the Chrome container, sure. Would you prefer that happen in this PR or that it be addressed in a subsequent PR? @wsill

Normally I would say in this PR but it might be better in a separate PR.

2021-05-10 14:04 UTC, jrittenh approved these changes

2021-05-10 14:08 UTC, merged